// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminStats = `-- name: AdminStats :one
SELECT
    (SELECT count(*) FROM payments WHERE status = 'pending')::bigint AS pending_payments,
    (SELECT count(*) FROM subscriptions
        WHERE current_period_end IS NOT NULL AND current_period_end > now())::bigint AS active_subscribers,
    (SELECT count(*) FROM subscriptions
        WHERE current_period_end IS NOT NULL
          AND current_period_end > now()
          AND current_period_end <= now() + interval '7 days')::bigint AS expiring_soon,
    (SELECT COALESCE(sum(amount_egp), 0) FROM payments
        WHERE status = 'confirmed'
          AND reviewed_at >= date_trunc('month', now()))::numeric AS revenue_this_month
`

type AdminStatsRow struct {
	PendingPayments   int64
	ActiveSubscribers int64
	ExpiringSoon      int64
	RevenueThisMonth  string
}

func (q *Queries) AdminStats(ctx context.Context) (AdminStatsRow, error) {
	row := q.db.QueryRow(ctx, adminStats)
	var i AdminStatsRow
	err := row.Scan(
		&i.PendingPayments,
		&i.ActiveSubscribers,
		&i.ExpiringSoon,
		&i.RevenueThisMonth,
	)
	return i, err
}

const getFarmDetail = `-- name: GetFarmDetail :one
SELECT f.id, f.name, f.created_at,
       s.plan, s.status, s.current_period_end
FROM farms f
LEFT JOIN subscriptions s ON s.farm_id = f.id
WHERE f.id = $1
`

type GetFarmDetailRow struct {
	ID               int32
	Name             string
	CreatedAt        pgtype.Timestamptz
	Plan             *string
	Status           *string
	CurrentPeriodEnd pgtype.Timestamptz
}

func (q *Queries) GetFarmDetail(ctx context.Context, id int32) (GetFarmDetailRow, error) {
	row := q.db.QueryRow(ctx, getFarmDetail, id)
	var i GetFarmDetailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodEnd,
	)
	return i, err
}

const listFarms = `-- name: ListFarms :many
SELECT f.id, f.name, f.created_at,
       (SELECT count(*) FROM farm_members m WHERE m.farm_id = f.id)::bigint AS member_count,
       s.plan, s.status, s.current_period_end
FROM farms f
LEFT JOIN subscriptions s ON s.farm_id = f.id
WHERE ($1::text IS NULL OR f.name ILIKE '%' || $1::text || '%')
ORDER BY f.created_at DESC, f.id DESC
LIMIT $3::int OFFSET $2::int
`

type ListFarmsParams struct {
	Q   *string
	Off int32
	Lim int32
}

type ListFarmsRow struct {
	ID               int32
	Name             string
	CreatedAt        pgtype.Timestamptz
	MemberCount      int64
	Plan             *string
	Status           *string
	CurrentPeriodEnd pgtype.Timestamptz
}

func (q *Queries) ListFarms(ctx context.Context, arg ListFarmsParams) ([]ListFarmsRow, error) {
	rows, err := q.db.Query(ctx, listFarms, arg.Q, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFarmsRow{}
	for rows.Next() {
		var i ListFarmsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.MemberCount,
			&i.Plan,
			&i.Status,
			&i.CurrentPeriodEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsDetailed = `-- name: ListPaymentsDetailed :many
SELECT p.id, p.plan, p.amount_egp, p.instapay_ref, p.screenshot_url, p.status, p.reviewed_by, p.reviewed_at, p.note, p.created_at, p.farm_id, p.created_by, f.name AS farm_name, u.phone_number AS submitted_by
FROM payments p
JOIN farms f ON f.id = p.farm_id
LEFT JOIN users u ON u.id = p.created_by
WHERE ($1::text IS NULL OR p.status = $1::text)
ORDER BY p.created_at DESC, p.id DESC
LIMIT $2::int
`

type ListPaymentsDetailedParams struct {
	Status *string
	Lim    int32
}

type ListPaymentsDetailedRow struct {
	ID            int32
	Plan          string
	AmountEgp     string
	InstapayRef   string
	ScreenshotUrl *string
	Status        string
	ReviewedBy    *int32
	ReviewedAt    pgtype.Timestamptz
	Note          *string
	CreatedAt     pgtype.Timestamptz
	FarmID        int32
	CreatedBy     *int32
	FarmName      string
	SubmittedBy   *string
}

func (q *Queries) ListPaymentsDetailed(ctx context.Context, arg ListPaymentsDetailedParams) ([]ListPaymentsDetailedRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsDetailed, arg.Status, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsDetailedRow{}
	for rows.Next() {
		var i ListPaymentsDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.Plan,
			&i.AmountEgp,
			&i.InstapayRef,
			&i.ScreenshotUrl,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.Note,
			&i.CreatedAt,
			&i.FarmID,
			&i.CreatedBy,
			&i.FarmName,
			&i.SubmittedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
