// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminStats = `-- name: AdminStats :one
SELECT
    (SELECT count(*) FROM payments WHERE status = 'pending')::bigint AS pending_payments,
    (SELECT count(*) FROM subscriptions
        WHERE current_period_end IS NOT NULL AND current_period_end > now())::bigint AS active_subscribers,
    (SELECT count(*) FROM subscriptions
        WHERE current_period_end IS NOT NULL
          AND current_period_end > now()
          AND current_period_end <= now() + interval '7 days')::bigint AS expiring_soon,
    (SELECT COALESCE(sum(amount_egp), 0) FROM payments
        WHERE status = 'confirmed'
          AND reviewed_at >= date_trunc('month', now()))::numeric AS revenue_this_month
`

type AdminStatsRow struct {
	PendingPayments   int64
	ActiveSubscribers int64
	ExpiringSoon      int64
	RevenueThisMonth  string
}

func (q *Queries) AdminStats(ctx context.Context) (AdminStatsRow, error) {
	row := q.db.QueryRow(ctx, adminStats)
	var i AdminStatsRow
	err := row.Scan(
		&i.PendingPayments,
		&i.ActiveSubscribers,
		&i.ExpiringSoon,
		&i.RevenueThisMonth,
	)
	return i, err
}

const getSubscriberDetail = `-- name: GetSubscriberDetail :one
SELECT u.id, u.phone_number, u.role, u.is_admin, u.created_at,
       s.plan, s.status, s.current_period_end
FROM users u
LEFT JOIN subscriptions s ON s.user_id = u.id
WHERE u.id = $1
`

type GetSubscriberDetailRow struct {
	ID               int32
	PhoneNumber      string
	Role             string
	IsAdmin          bool
	CreatedAt        pgtype.Timestamptz
	Plan             *string
	Status           *string
	CurrentPeriodEnd pgtype.Timestamptz
}

func (q *Queries) GetSubscriberDetail(ctx context.Context, id int32) (GetSubscriberDetailRow, error) {
	row := q.db.QueryRow(ctx, getSubscriberDetail, id)
	var i GetSubscriberDetailRow
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Role,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodEnd,
	)
	return i, err
}

const listPaymentsDetailed = `-- name: ListPaymentsDetailed :many
SELECT p.id, p.user_id, p.plan, p.amount_egp, p.instapay_ref, p.screenshot_url, p.status, p.reviewed_by, p.reviewed_at, p.note, p.created_at, u.phone_number
FROM payments p
JOIN users u ON u.id = p.user_id
WHERE ($1::text IS NULL OR p.status = $1::text)
ORDER BY p.created_at DESC, p.id DESC
LIMIT $2::int
`

type ListPaymentsDetailedParams struct {
	Status *string
	Lim    int32
}

type ListPaymentsDetailedRow struct {
	ID            int32
	UserID        int32
	Plan          string
	AmountEgp     string
	InstapayRef   string
	ScreenshotUrl *string
	Status        string
	ReviewedBy    *int32
	ReviewedAt    pgtype.Timestamptz
	Note          *string
	CreatedAt     pgtype.Timestamptz
	PhoneNumber   string
}

func (q *Queries) ListPaymentsDetailed(ctx context.Context, arg ListPaymentsDetailedParams) ([]ListPaymentsDetailedRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsDetailed, arg.Status, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsDetailedRow{}
	for rows.Next() {
		var i ListPaymentsDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Plan,
			&i.AmountEgp,
			&i.InstapayRef,
			&i.ScreenshotUrl,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.Note,
			&i.CreatedAt,
			&i.PhoneNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribers = `-- name: ListSubscribers :many
SELECT u.id, u.phone_number, u.role, u.created_at,
       s.plan, s.status, s.current_period_end
FROM users u
LEFT JOIN subscriptions s ON s.user_id = u.id
WHERE ($1::text IS NULL OR u.phone_number ILIKE '%' || $1::text || '%')
ORDER BY u.created_at DESC, u.id DESC
LIMIT $3::int OFFSET $2::int
`

type ListSubscribersParams struct {
	Phone *string
	Off   int32
	Lim   int32
}

type ListSubscribersRow struct {
	ID               int32
	PhoneNumber      string
	Role             string
	CreatedAt        pgtype.Timestamptz
	Plan             *string
	Status           *string
	CurrentPeriodEnd pgtype.Timestamptz
}

func (q *Queries) ListSubscribers(ctx context.Context, arg ListSubscribersParams) ([]ListSubscribersRow, error) {
	rows, err := q.db.Query(ctx, listSubscribers, arg.Phone, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscribersRow{}
	for rows.Next() {
		var i ListSubscribersRow
		if err := rows.Scan(
			&i.ID,
			&i.PhoneNumber,
			&i.Role,
			&i.CreatedAt,
			&i.Plan,
			&i.Status,
			&i.CurrentPeriodEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
