// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: animals.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnimal = `-- name: CreateAnimal :one
INSERT INTO animals (barcode, user_id)
VALUES ($1, $2)
RETURNING id, barcode, created_at, updated_at
`

type CreateAnimalParams struct {
	Barcode string
	UserID  int32
}

type CreateAnimalRow struct {
	ID        int32
	Barcode   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateAnimal(ctx context.Context, arg CreateAnimalParams) (CreateAnimalRow, error) {
	row := q.db.QueryRow(ctx, createAnimal, arg.Barcode, arg.UserID)
	var i CreateAnimalRow
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnimal = `-- name: DeleteAnimal :execrows
DELETE FROM animals WHERE id = $1 AND user_id = $2
`

type DeleteAnimalParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeleteAnimal(ctx context.Context, arg DeleteAnimalParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnimal, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnimal = `-- name: GetAnimal :one
SELECT a.id, a.barcode, a.created_at, a.updated_at,
       (SELECT count(*) FROM animal_notes n WHERE n.animal_id = a.id)::bigint AS note_count
FROM animals a
WHERE a.id = $1 AND a.user_id = $2
`

type GetAnimalParams struct {
	ID     int32
	UserID int32
}

type GetAnimalRow struct {
	ID        int32
	Barcode   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	NoteCount int64
}

func (q *Queries) GetAnimal(ctx context.Context, arg GetAnimalParams) (GetAnimalRow, error) {
	row := q.db.QueryRow(ctx, getAnimal, arg.ID, arg.UserID)
	var i GetAnimalRow
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NoteCount,
	)
	return i, err
}

const getAnimalByBarcode = `-- name: GetAnimalByBarcode :one
SELECT a.id, a.barcode, a.created_at, a.updated_at,
       (SELECT count(*) FROM animal_notes n WHERE n.animal_id = a.id)::bigint AS note_count
FROM animals a
WHERE a.barcode = $1 AND a.user_id = $2
`

type GetAnimalByBarcodeParams struct {
	Barcode string
	UserID  int32
}

type GetAnimalByBarcodeRow struct {
	ID        int32
	Barcode   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	NoteCount int64
}

func (q *Queries) GetAnimalByBarcode(ctx context.Context, arg GetAnimalByBarcodeParams) (GetAnimalByBarcodeRow, error) {
	row := q.db.QueryRow(ctx, getAnimalByBarcode, arg.Barcode, arg.UserID)
	var i GetAnimalByBarcodeRow
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NoteCount,
	)
	return i, err
}

const getAnimalOwner = `-- name: GetAnimalOwner :one
SELECT id, user_id FROM animals WHERE id = $1
`

type GetAnimalOwnerRow struct {
	ID     int32
	UserID int32
}

// Unscoped lookup used only to resolve a vet's access via the animal's farmer.
func (q *Queries) GetAnimalOwner(ctx context.Context, id int32) (GetAnimalOwnerRow, error) {
	row := q.db.QueryRow(ctx, getAnimalOwner, id)
	var i GetAnimalOwnerRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const listAnimals = `-- name: ListAnimals :many
SELECT a.id, a.barcode, a.created_at, a.updated_at,
       (SELECT count(*) FROM animal_notes n WHERE n.animal_id = a.id)::bigint AS note_count
FROM animals a
WHERE a.user_id = $1
  AND ($2::timestamptz IS NULL
       OR (a.created_at, a.id) < ($2::timestamptz, $3::int))
ORDER BY a.created_at DESC, a.id DESC
LIMIT $4::int
`

type ListAnimalsParams struct {
	UserID     int32
	CursorTime pgtype.Timestamptz
	CursorID   int32
	Lim        int32
}

type ListAnimalsRow struct {
	ID        int32
	Barcode   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	NoteCount int64
}

func (q *Queries) ListAnimals(ctx context.Context, arg ListAnimalsParams) ([]ListAnimalsRow, error) {
	rows, err := q.db.Query(ctx, listAnimals,
		arg.UserID,
		arg.CursorTime,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnimalsRow{}
	for rows.Next() {
		var i ListAnimalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Barcode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnimal = `-- name: UpdateAnimal :one
UPDATE animals
SET barcode = $1, updated_at = now()
WHERE id = $2 AND user_id = $3
RETURNING id, barcode, created_at, updated_at
`

type UpdateAnimalParams struct {
	Barcode string
	ID      int32
	UserID  int32
}

type UpdateAnimalRow struct {
	ID        int32
	Barcode   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateAnimal(ctx context.Context, arg UpdateAnimalParams) (UpdateAnimalRow, error) {
	row := q.db.QueryRow(ctx, updateAnimal, arg.Barcode, arg.ID, arg.UserID)
	var i UpdateAnimalRow
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
