// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"
)

const createAudit = `-- name: CreateAudit :exec
INSERT INTO admin_audit (admin_id, action, target_user, payment_id, detail)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAuditParams struct {
	AdminID    int32
	Action     string
	TargetUser *int32
	PaymentID  *int32
	Detail     *string
}

func (q *Queries) CreateAudit(ctx context.Context, arg CreateAuditParams) error {
	_, err := q.db.Exec(ctx, createAudit,
		arg.AdminID,
		arg.Action,
		arg.TargetUser,
		arg.PaymentID,
		arg.Detail,
	)
	return err
}
