// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: farms.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMember = `-- name: AddMember :one
INSERT INTO farm_members (farm_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, farm_id, user_id, role, created_at
`

type AddMemberParams struct {
	FarmID int32
	UserID int32
	Role   string
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (FarmMember, error) {
	row := q.db.QueryRow(ctx, addMember, arg.FarmID, arg.UserID, arg.Role)
	var i FarmMember
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const countFarmAdmins = `-- name: CountFarmAdmins :one
SELECT count(*)::bigint AS admins FROM farm_members WHERE farm_id = $1 AND role = 'admin'
`

func (q *Queries) CountFarmAdmins(ctx context.Context, farmID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countFarmAdmins, farmID)
	var admins int64
	err := row.Scan(&admins)
	return admins, err
}

const createFarm = `-- name: CreateFarm :one
INSERT INTO farms (name) VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateFarm(ctx context.Context, name string) (Farm, error) {
	row := q.db.QueryRow(ctx, createFarm, name)
	var i Farm
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getFarm = `-- name: GetFarm :one
SELECT id, name, created_at FROM farms WHERE id = $1
`

func (q *Queries) GetFarm(ctx context.Context, id int32) (Farm, error) {
	row := q.db.QueryRow(ctx, getFarm, id)
	var i Farm
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT id, farm_id, user_id, role, created_at FROM farm_members WHERE farm_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	FarmID int32
	UserID int32
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (FarmMember, error) {
	row := q.db.QueryRow(ctx, getMember, arg.FarmID, arg.UserID)
	var i FarmMember
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getMembershipByUser = `-- name: GetMembershipByUser :one
SELECT farm_id, role FROM farm_members WHERE user_id = $1
`

type GetMembershipByUserRow struct {
	FarmID int32
	Role   string
}

// The caller's farm context: which farm they belong to and their role there.
func (q *Queries) GetMembershipByUser(ctx context.Context, userID int32) (GetMembershipByUserRow, error) {
	row := q.db.QueryRow(ctx, getMembershipByUser, userID)
	var i GetMembershipByUserRow
	err := row.Scan(&i.FarmID, &i.Role)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT m.user_id, m.role, m.created_at, u.phone_number
FROM farm_members m
JOIN users u ON u.id = m.user_id
WHERE m.farm_id = $1
ORDER BY m.created_at ASC, m.user_id ASC
`

type ListMembersRow struct {
	UserID      int32
	Role        string
	CreatedAt   pgtype.Timestamptz
	PhoneNumber string
}

func (q *Queries) ListMembers(ctx context.Context, farmID int32) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.PhoneNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :execrows
DELETE FROM farm_members WHERE farm_id = $1 AND user_id = $2 AND role <> 'admin'
`

type RemoveMemberParams struct {
	FarmID int32
	UserID int32
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMember, arg.FarmID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
