// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlc

import (
	"context"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one
INSERT INTO idempotency_keys (farm_id, key, request_hash)
VALUES ($1, $2, $3)
ON CONFLICT (farm_id, key) DO NOTHING
RETURNING farm_id, key, request_hash, status_code, response_body, created_at, completed_at
`

type ClaimIdempotencyKeyParams struct {
	FarmID      int32
	Key         string
	RequestHash string
}

// Claims a key for the caller's farm. Returns no row when the key is already
// taken — the caller then reads the stored response (or reports "in progress").
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey, arg.FarmID, arg.Key, arg.RequestHash)
	var i IdempotencyKey
	err := row.Scan(
		&i.FarmID,
		&i.Key,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET status_code = $1, response_body = $2, completed_at = now()
WHERE farm_id = $3 AND key = $4
`

type CompleteIdempotencyKeyParams struct {
	StatusCode   *int32
	ResponseBody []byte
	FarmID       int32
	Key          string
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.StatusCode,
		arg.ResponseBody,
		arg.FarmID,
		arg.Key,
	)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT farm_id, key, request_hash, status_code, response_body, created_at, completed_at FROM idempotency_keys WHERE farm_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	FarmID int32
	Key    string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.FarmID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.FarmID,
		&i.Key,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const purgeIdempotencyKeys = `-- name: PurgeIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE created_at < now() - make_interval(hours => $1::int)
`

// Drops keys past the replay window (§6.1); the client has long since given up.
func (q *Queries) PurgeIdempotencyKeys(ctx context.Context, olderThanHours int32) (int64, error) {
	result, err := q.db.Exec(ctx, purgeIdempotencyKeys, olderThanHours)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseIdempotencyKey = `-- name: ReleaseIdempotencyKey :exec
DELETE FROM idempotency_keys WHERE farm_id = $1 AND key = $2
`

type ReleaseIdempotencyKeyParams struct {
	FarmID int32
	Key    string
}

// Frees a claim whose request failed, so the client's retry can run for real.
func (q *Queries) ReleaseIdempotencyKey(ctx context.Context, arg ReleaseIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, releaseIdempotencyKey, arg.FarmID, arg.Key)
	return err
}
