// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO doctor_invites (farm_id, token, doctor_label, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, farm_id, token, doctor_label, status, expires_at, created_by, created_at, ended_at, ended_by
`

type CreateInviteParams struct {
	FarmID      int32
	Token       string
	DoctorLabel string
	ExpiresAt   pgtype.Timestamptz
	CreatedBy   *int32
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (DoctorInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.FarmID,
		arg.Token,
		arg.DoctorLabel,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i DoctorInvite
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.Token,
		&i.DoctorLabel,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.EndedAt,
		&i.EndedBy,
	)
	return i, err
}

const endInvite = `-- name: EndInvite :one
UPDATE doctor_invites
SET status = 'ended', ended_at = now(), ended_by = $1
WHERE id = $2 AND farm_id = $3 AND status = 'active'
RETURNING id, farm_id, token, doctor_label, status, expires_at, created_by, created_at, ended_at, ended_by
`

type EndInviteParams struct {
	EndedBy *int32
	ID      int32
	FarmID  int32
}

func (q *Queries) EndInvite(ctx context.Context, arg EndInviteParams) (DoctorInvite, error) {
	row := q.db.QueryRow(ctx, endInvite, arg.EndedBy, arg.ID, arg.FarmID)
	var i DoctorInvite
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.Token,
		&i.DoctorLabel,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.EndedAt,
		&i.EndedBy,
	)
	return i, err
}

const getActiveInvite = `-- name: GetActiveInvite :one
SELECT id, farm_id, token, doctor_label, status, expires_at, created_by, created_at, ended_at, ended_by FROM doctor_invites
WHERE id = $1 AND status = 'active'
  AND (expires_at IS NULL OR expires_at > now())
`

// Used by the doctor-session middleware on every request → instant revocation.
func (q *Queries) GetActiveInvite(ctx context.Context, id int32) (DoctorInvite, error) {
	row := q.db.QueryRow(ctx, getActiveInvite, id)
	var i DoctorInvite
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.Token,
		&i.DoctorLabel,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.EndedAt,
		&i.EndedBy,
	)
	return i, err
}

const getInvite = `-- name: GetInvite :one
SELECT id, farm_id, token, doctor_label, status, expires_at, created_by, created_at, ended_at, ended_by FROM doctor_invites WHERE id = $1
`

func (q *Queries) GetInvite(ctx context.Context, id int32) (DoctorInvite, error) {
	row := q.db.QueryRow(ctx, getInvite, id)
	var i DoctorInvite
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.Token,
		&i.DoctorLabel,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.EndedAt,
		&i.EndedBy,
	)
	return i, err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT id, farm_id, token, doctor_label, status, expires_at, created_by, created_at, ended_at, ended_by FROM doctor_invites WHERE token = $1
`

func (q *Queries) GetInviteByToken(ctx context.Context, token string) (DoctorInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, token)
	var i DoctorInvite
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.Token,
		&i.DoctorLabel,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.EndedAt,
		&i.EndedBy,
	)
	return i, err
}

const listInvitesByFarm = `-- name: ListInvitesByFarm :many
SELECT i.id, i.farm_id, i.token, i.doctor_label, i.status, i.expires_at, i.created_by, i.created_at, i.ended_at, i.ended_by,
       (SELECT count(*) FROM animal_notes n WHERE n.author_invite_id = i.id)::bigint AS note_count
FROM doctor_invites i
WHERE i.farm_id = $1
ORDER BY i.created_at DESC, i.id DESC
`

type ListInvitesByFarmRow struct {
	ID          int32
	FarmID      int32
	Token       string
	DoctorLabel string
	Status      string
	ExpiresAt   pgtype.Timestamptz
	CreatedBy   *int32
	CreatedAt   pgtype.Timestamptz
	EndedAt     pgtype.Timestamptz
	EndedBy     *int32
	NoteCount   int64
}

// The farm's "who did what" history, with how many notes each doctor wrote.
func (q *Queries) ListInvitesByFarm(ctx context.Context, farmID int32) ([]ListInvitesByFarmRow, error) {
	rows, err := q.db.Query(ctx, listInvitesByFarm, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitesByFarmRow{}
	for rows.Next() {
		var i ListInvitesByFarmRow
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.Token,
			&i.DoctorLabel,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.EndedAt,
			&i.EndedBy,
			&i.NoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
