// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAudit struct {
	ID         int32
	AdminID    int32
	Action     string
	TargetUser *int32
	PaymentID  *int32
	Detail     *string
	CreatedAt  pgtype.Timestamptz
}

type Animal struct {
	ID        int32
	Barcode   string
	UserID    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AnimalNote struct {
	ID         int32
	AnimalID   int32
	Notes      string
	AuthorID   int32
	AuthorRole string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	VisitID    *int32
}

type Payment struct {
	ID            int32
	UserID        int32
	Plan          string
	AmountEgp     string
	InstapayRef   string
	ScreenshotUrl *string
	Status        string
	ReviewedBy    *int32
	ReviewedAt    pgtype.Timestamptz
	Note          *string
	CreatedAt     pgtype.Timestamptz
}

type Subscription struct {
	ID               int32
	UserID           int32
	Plan             string
	Status           string
	CurrentPeriodEnd pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type User struct {
	ID                     int32
	PhoneNumber            string
	Password               string
	RefreshToken           *string
	RefreshTokenExpiryTime pgtype.Timestamptz
	IsAdmin                bool
	Role                   string
	CreatedAt              pgtype.Timestamptz
}

type Visit struct {
	ID            int32
	FarmerID      int32
	VetID         *int32
	LocationType  string
	LocationLabel *string
	Status        string
	OpenedAt      pgtype.Timestamptz
	ClosedAt      pgtype.Timestamptz
}
