// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAudit struct {
	ID         int32
	AdminID    int32
	Action     string
	TargetUser *int32
	PaymentID  *int32
	Detail     *string
	CreatedAt  pgtype.Timestamptz
}

type Animal struct {
	ID        int32
	Barcode   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	FarmID    int32
}

type AnimalNote struct {
	ID             int32
	AnimalID       int32
	Notes          string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	AuthorKind     string
	AuthorUserID   *int32
	AuthorInviteID *int32
	AuthorLabel    string
}

type DoctorInvite struct {
	ID          int32
	FarmID      int32
	Token       string
	DoctorLabel string
	Status      string
	ExpiresAt   pgtype.Timestamptz
	CreatedBy   *int32
	CreatedAt   pgtype.Timestamptz
	EndedAt     pgtype.Timestamptz
	EndedBy     *int32
}

type Farm struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamptz
}

type FarmMember struct {
	ID        int32
	FarmID    int32
	UserID    int32
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Payment struct {
	ID            int32
	Plan          string
	AmountEgp     string
	InstapayRef   string
	ScreenshotUrl *string
	Status        string
	ReviewedBy    *int32
	ReviewedAt    pgtype.Timestamptz
	Note          *string
	CreatedAt     pgtype.Timestamptz
	FarmID        int32
	CreatedBy     *int32
}

type Subscription struct {
	ID               int32
	Plan             string
	Status           string
	CurrentPeriodEnd pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	FarmID           int32
}

type User struct {
	ID                     int32
	PhoneNumber            string
	Password               string
	RefreshToken           *string
	RefreshTokenExpiryTime pgtype.Timestamptz
	IsAdmin                bool
	CreatedAt              pgtype.Timestamptz
}
