// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO animal_notes (animal_id, notes, author_id, author_role, visit_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, animal_id, notes, author_id, author_role, created_at, updated_at, visit_id
`

type CreateNoteParams struct {
	AnimalID   int32
	Notes      string
	AuthorID   int32
	AuthorRole string
	VisitID    *int32
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (AnimalNote, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.AnimalID,
		arg.Notes,
		arg.AuthorID,
		arg.AuthorRole,
		arg.VisitID,
	)
	var i AnimalNote
	err := row.Scan(
		&i.ID,
		&i.AnimalID,
		&i.Notes,
		&i.AuthorID,
		&i.AuthorRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VisitID,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :execrows
DELETE FROM animal_notes
WHERE id = $1 AND animal_id = $2 AND author_id = $3
`

type DeleteNoteParams struct {
	ID       int32
	AnimalID int32
	AuthorID int32
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, arg.ID, arg.AnimalID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNote = `-- name: GetNote :one
SELECT n.id, n.animal_id, n.notes, n.author_id, n.author_role, n.created_at, n.updated_at, n.visit_id FROM animal_notes n
JOIN animals a ON a.id = n.animal_id
WHERE n.id = $1 AND n.animal_id = $2 AND a.user_id = $3
`

type GetNoteParams struct {
	ID       int32
	AnimalID int32
	OwnerID  int32
}

func (q *Queries) GetNote(ctx context.Context, arg GetNoteParams) (AnimalNote, error) {
	row := q.db.QueryRow(ctx, getNote, arg.ID, arg.AnimalID, arg.OwnerID)
	var i AnimalNote
	err := row.Scan(
		&i.ID,
		&i.AnimalID,
		&i.Notes,
		&i.AuthorID,
		&i.AuthorRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VisitID,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT n.id, n.animal_id, n.notes, n.author_id, n.author_role, n.created_at, n.updated_at, n.visit_id FROM animal_notes n
JOIN animals a ON a.id = n.animal_id
WHERE n.animal_id = $1 AND a.user_id = $2
  AND ($3::timestamptz IS NULL
       OR (n.created_at, n.id) < ($3::timestamptz, $4::int))
ORDER BY n.created_at DESC, n.id DESC
LIMIT $5::int
`

type ListNotesParams struct {
	AnimalID   int32
	OwnerID    int32
	CursorTime pgtype.Timestamptz
	CursorID   int32
	Lim        int32
}

func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]AnimalNote, error) {
	rows, err := q.db.Query(ctx, listNotes,
		arg.AnimalID,
		arg.OwnerID,
		arg.CursorTime,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnimalNote{}
	for rows.Next() {
		var i AnimalNote
		if err := rows.Scan(
			&i.ID,
			&i.AnimalID,
			&i.Notes,
			&i.AuthorID,
			&i.AuthorRole,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VisitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE animal_notes
SET notes = $1, updated_at = now()
WHERE id = $2 AND animal_id = $3 AND author_id = $4
RETURNING id, animal_id, notes, author_id, author_role, created_at, updated_at, visit_id
`

type UpdateNoteParams struct {
	Notes    string
	ID       int32
	AnimalID int32
	AuthorID int32
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (AnimalNote, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.Notes,
		arg.ID,
		arg.AnimalID,
		arg.AuthorID,
	)
	var i AnimalNote
	err := row.Scan(
		&i.ID,
		&i.AnimalID,
		&i.Notes,
		&i.AuthorID,
		&i.AuthorRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VisitID,
	)
	return i, err
}
