// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (user_id, plan, amount_egp, instapay_ref, screenshot_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, plan, amount_egp, instapay_ref, screenshot_url, status, reviewed_by, reviewed_at, note, created_at
`

type CreatePaymentParams struct {
	UserID        int32
	Plan          string
	AmountEgp     string
	InstapayRef   string
	ScreenshotUrl *string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.Plan,
		arg.AmountEgp,
		arg.InstapayRef,
		arg.ScreenshotUrl,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.AmountEgp,
		&i.InstapayRef,
		&i.ScreenshotUrl,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, user_id, plan, amount_egp, instapay_ref, screenshot_url, status, reviewed_by, reviewed_at, note, created_at FROM payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id int32) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.AmountEgp,
		&i.InstapayRef,
		&i.ScreenshotUrl,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByRef = `-- name: GetPaymentByRef :one
SELECT id, user_id, plan, amount_egp, instapay_ref, screenshot_url, status, reviewed_by, reviewed_at, note, created_at FROM payments WHERE instapay_ref = $1
`

func (q *Queries) GetPaymentByRef(ctx context.Context, instapayRef string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByRef, instapayRef)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.AmountEgp,
		&i.InstapayRef,
		&i.ScreenshotUrl,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, user_id, plan, amount_egp, instapay_ref, screenshot_url, status, reviewed_by, reviewed_at, note, created_at FROM payments
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::timestamptz IS NULL
       OR (created_at, id) < ($2::timestamptz, $3::int))
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type ListPaymentsParams struct {
	Status     *string
	CursorTime pgtype.Timestamptz
	CursorID   int32
	Lim        int32
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments,
		arg.Status,
		arg.CursorTime,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Plan,
			&i.AmountEgp,
			&i.InstapayRef,
			&i.ScreenshotUrl,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByUser = `-- name: ListPaymentsByUser :many
SELECT id, user_id, plan, amount_egp, instapay_ref, screenshot_url, status, reviewed_by, reviewed_at, note, created_at FROM payments
WHERE user_id = $1
  AND ($2::timestamptz IS NULL
       OR (created_at, id) < ($2::timestamptz, $3::int))
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type ListPaymentsByUserParams struct {
	UserID     int32
	CursorTime pgtype.Timestamptz
	CursorID   int32
	Lim        int32
}

func (q *Queries) ListPaymentsByUser(ctx context.Context, arg ListPaymentsByUserParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByUser,
		arg.UserID,
		arg.CursorTime,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Plan,
			&i.AmountEgp,
			&i.InstapayRef,
			&i.ScreenshotUrl,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewPayment = `-- name: ReviewPayment :one
UPDATE payments
SET status = $1, reviewed_by = $2, reviewed_at = now(), note = $3
WHERE id = $4 AND status = 'pending'
RETURNING id, user_id, plan, amount_egp, instapay_ref, screenshot_url, status, reviewed_by, reviewed_at, note, created_at
`

type ReviewPaymentParams struct {
	Status     string
	ReviewedBy *int32
	Note       *string
	ID         int32
}

// Marks a pending payment confirmed/rejected. Returns no row if not pending (idempotent guard).
func (q *Queries) ReviewPayment(ctx context.Context, arg ReviewPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, reviewPayment,
		arg.Status,
		arg.ReviewedBy,
		arg.Note,
		arg.ID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.AmountEgp,
		&i.InstapayRef,
		&i.ScreenshotUrl,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
