// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearRefreshToken = `-- name: ClearRefreshToken :exec
UPDATE users
SET refresh_token = NULL, refresh_token_expiry_time = NULL
WHERE id = $1
`

func (q *Queries) ClearRefreshToken(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, clearRefreshToken, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone_number, password)
VALUES ($1, $2)
RETURNING id, phone_number, password, refresh_token, refresh_token_expiry_time, is_admin, created_at
`

type CreateUserParams struct {
	PhoneNumber string
	Password    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.PhoneNumber, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Password,
		&i.RefreshToken,
		&i.RefreshTokenExpiryTime,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone_number, password, refresh_token, refresh_token_expiry_time, is_admin, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Password,
		&i.RefreshToken,
		&i.RefreshTokenExpiryTime,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone_number, password, refresh_token, refresh_token_expiry_time, is_admin, created_at FROM users WHERE phone_number = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Password,
		&i.RefreshToken,
		&i.RefreshTokenExpiryTime,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByRefreshToken = `-- name: GetUserByRefreshToken :one
SELECT id, phone_number, password, refresh_token, refresh_token_expiry_time, is_admin, created_at FROM users
WHERE refresh_token = $1
  AND refresh_token_expiry_time IS NOT NULL
  AND refresh_token_expiry_time > now()
`

func (q *Queries) GetUserByRefreshToken(ctx context.Context, refreshToken *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByRefreshToken, refreshToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Password,
		&i.RefreshToken,
		&i.RefreshTokenExpiryTime,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const setAdminByPhone = `-- name: SetAdminByPhone :one
UPDATE users SET is_admin = TRUE WHERE phone_number = $1
RETURNING id, phone_number, password, refresh_token, refresh_token_expiry_time, is_admin, created_at
`

func (q *Queries) SetAdminByPhone(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, setAdminByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Password,
		&i.RefreshToken,
		&i.RefreshTokenExpiryTime,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const setRefreshToken = `-- name: SetRefreshToken :exec
UPDATE users
SET refresh_token = $1,
    refresh_token_expiry_time = $2
WHERE id = $3
`

type SetRefreshTokenParams struct {
	RefreshToken           *string
	RefreshTokenExpiryTime pgtype.Timestamptz
	ID                     int32
}

func (q *Queries) SetRefreshToken(ctx context.Context, arg SetRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, setRefreshToken, arg.RefreshToken, arg.RefreshTokenExpiryTime, arg.ID)
	return err
}
