// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: visits.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeVisit = `-- name: CloseVisit :one
UPDATE visits
SET status = 'closed', closed_at = now()
WHERE id = $1 AND farmer_id = $2 AND status = 'open'
RETURNING id, farmer_id, vet_id, location_type, location_label, status, opened_at, closed_at
`

type CloseVisitParams struct {
	ID       int32
	FarmerID int32
}

func (q *Queries) CloseVisit(ctx context.Context, arg CloseVisitParams) (Visit, error) {
	row := q.db.QueryRow(ctx, closeVisit, arg.ID, arg.FarmerID)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.FarmerID,
		&i.VetID,
		&i.LocationType,
		&i.LocationLabel,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
	)
	return i, err
}

const createVisit = `-- name: CreateVisit :one
INSERT INTO visits (farmer_id, vet_id, location_type, location_label)
VALUES ($1, $2, $3, $4)
RETURNING id, farmer_id, vet_id, location_type, location_label, status, opened_at, closed_at
`

type CreateVisitParams struct {
	FarmerID      int32
	VetID         *int32
	LocationType  string
	LocationLabel *string
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) (Visit, error) {
	row := q.db.QueryRow(ctx, createVisit,
		arg.FarmerID,
		arg.VetID,
		arg.LocationType,
		arg.LocationLabel,
	)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.FarmerID,
		&i.VetID,
		&i.LocationType,
		&i.LocationLabel,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getOpenVisitForVet = `-- name: GetOpenVisitForVet :one
SELECT id, farmer_id, vet_id, location_type, location_label, status, opened_at, closed_at FROM visits
WHERE id = $1 AND vet_id = $2 AND status = 'open'
`

type GetOpenVisitForVetParams struct {
	ID    int32
	VetID *int32
}

func (q *Queries) GetOpenVisitForVet(ctx context.Context, arg GetOpenVisitForVetParams) (Visit, error) {
	row := q.db.QueryRow(ctx, getOpenVisitForVet, arg.ID, arg.VetID)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.FarmerID,
		&i.VetID,
		&i.LocationType,
		&i.LocationLabel,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getVisitForFarmer = `-- name: GetVisitForFarmer :one
SELECT id, farmer_id, vet_id, location_type, location_label, status, opened_at, closed_at FROM visits WHERE id = $1 AND farmer_id = $2
`

type GetVisitForFarmerParams struct {
	ID       int32
	FarmerID int32
}

func (q *Queries) GetVisitForFarmer(ctx context.Context, arg GetVisitForFarmerParams) (Visit, error) {
	row := q.db.QueryRow(ctx, getVisitForFarmer, arg.ID, arg.FarmerID)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.FarmerID,
		&i.VetID,
		&i.LocationType,
		&i.LocationLabel,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
	)
	return i, err
}

const listVisitsByFarmer = `-- name: ListVisitsByFarmer :many
SELECT id, farmer_id, vet_id, location_type, location_label, status, opened_at, closed_at FROM visits
WHERE farmer_id = $1
  AND ($2::timestamptz IS NULL
       OR (opened_at, id) < ($2::timestamptz, $3::int))
ORDER BY opened_at DESC, id DESC
LIMIT $4::int
`

type ListVisitsByFarmerParams struct {
	FarmerID   int32
	CursorTime pgtype.Timestamptz
	CursorID   int32
	Lim        int32
}

func (q *Queries) ListVisitsByFarmer(ctx context.Context, arg ListVisitsByFarmerParams) ([]Visit, error) {
	rows, err := q.db.Query(ctx, listVisitsByFarmer,
		arg.FarmerID,
		arg.CursorTime,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Visit{}
	for rows.Next() {
		var i Visit
		if err := rows.Scan(
			&i.ID,
			&i.FarmerID,
			&i.VetID,
			&i.LocationType,
			&i.LocationLabel,
			&i.Status,
			&i.OpenedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisitsByVet = `-- name: ListVisitsByVet :many
SELECT id, farmer_id, vet_id, location_type, location_label, status, opened_at, closed_at FROM visits
WHERE vet_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::timestamptz IS NULL
       OR (opened_at, id) < ($3::timestamptz, $4::int))
ORDER BY opened_at DESC, id DESC
LIMIT $5::int
`

type ListVisitsByVetParams struct {
	VetID      *int32
	Status     *string
	CursorTime pgtype.Timestamptz
	CursorID   int32
	Lim        int32
}

func (q *Queries) ListVisitsByVet(ctx context.Context, arg ListVisitsByVetParams) ([]Visit, error) {
	rows, err := q.db.Query(ctx, listVisitsByVet,
		arg.VetID,
		arg.Status,
		arg.CursorTime,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Visit{}
	for rows.Next() {
		var i Visit
		if err := rows.Scan(
			&i.ID,
			&i.FarmerID,
			&i.VetID,
			&i.LocationType,
			&i.LocationLabel,
			&i.Status,
			&i.OpenedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vetHasOpenVisitWithFarmer = `-- name: VetHasOpenVisitWithFarmer :one
SELECT EXISTS (
    SELECT 1 FROM visits
    WHERE vet_id = $1 AND farmer_id = $2 AND status = 'open'
) AS has
`

type VetHasOpenVisitWithFarmerParams struct {
	VetID    *int32
	FarmerID int32
}

func (q *Queries) VetHasOpenVisitWithFarmer(ctx context.Context, arg VetHasOpenVisitWithFarmerParams) (bool, error) {
	row := q.db.QueryRow(ctx, vetHasOpenVisitWithFarmer, arg.VetID, arg.FarmerID)
	var has bool
	err := row.Scan(&has)
	return has, err
}
